plugins:
  - stylelint-prettier
extends:
  - stylelint-config-standard-scss
  - stylelint-config-recess-order
  - stylelint-prettier/recommended
  - stylelint-config-prettier
ignoreFiles:
  - "**/node_modules/**"
