name: Lint codes

on:
  pull_request:
    branches:
      - main

env:
  workdir: client
  node-version: lts/*

jobs:
  run-linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.workdir }}
    permissions:
      contents: 'read'
      pull-requests: 'read'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/filters.yml
      - name: Setup Node.js environment
        if: steps.changes.outputs.client == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install Dependencies
        if: steps.changes.outputs.client == 'true'
        run: yarn install --immutable
      - name: eslint
        if: steps.changes.outputs.client == 'true'
        run: yarn run lint --max-warnings=0
      - name: style lint
        if: steps.changes.outputs.client == 'true'
        run: yarn run lint:style
