name: Test Storybook

on:
  pull_request:
    branches:
      - main
    paths:
      - 'components/**/*.tsx'
      - 'stories/**/*.stories.tsx'
      - 'styles/**/*.scss'
      - 'package.json'
      - 'yarn.lock'
      - '.storybook/*'

env:
  workdir: client
  node-version: lts/*

jobs:
  front-filter:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      pull-requests: 'read'
    outputs:
      client: ${{ steps.changes.outputs.client }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/filters.yml
  run-build-storybook:
    runs-on: ubuntu-latest
    needs: front-filter
    if: needs.front-filter.outputs.client == 'true'
    defaults:
      run:
        working-directory: ${{ env.workdir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Build Storybook
        run: yarn run build-storybook
  run-build-storybook-check:
    if: ${{ ! failure() }}
    needs: run-build-storybook
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build Storybook is successfully executed. "
