name: Prettier codes

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'

env:
  workdir: client

jobs:
  run-formatter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.workdir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Format style codes
        run: yarn run lint:style-fix
      - name: Format the code
        run: yarn run fmt
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "fix(front): auto-fixable format by github-actions"
