name: Lint codes

on:
  pull_request:
    branches:
      - main
    paths:
      - 'front/**'

env:
  workdir: front

jobs:
  run-linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.workdir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --immutable
      - name: eslint
        run: yarn run lint --max-warnings=0
      - name: style lint
        run: yarn run lint:style
