name: Test codes(Server)

on:
  pull_request:
    branches:
      - main

env:
  workdir: server
  go-version: ">=1.17.0"

jobs:
  server-filter:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      pull-requests: 'read'
    outputs:
      server: ${{ steps.changes.outputs.server }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/filters.yml
  run-test:
    runs-on: ubuntu-latest
    needs: server-filter
    if: needs.server-filter.outputs.server == 'true'
    defaults:
      run:
        working-directory: ${{ env.workdir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      - name: Install dependencies
        run: go install
      - name: Run test
        run: go test ./...
  run-test-check:
    if: ${{ ! failure() }}
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test is successfully executed. "
