name: auto generate design tokens from data.json

on:
  push:
    paths:
      - front/**

env:
  workdir: front

jobs:
  run-style-dictionary:
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'auto/design-tokens')
    defaults:
      run:
        working-directory: ${{ env.workdir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Add style-dictionary
        run: yarn add -D style-dictionary
      - name: run style-dictionary
        run: yarn style-dictionary build --config ./tokens/data.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            feat(front): Update design tokens
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: auto/design-tokens
          base: main
          delete-branch: false
          title: |
            feat(front): Update design tokens
          body: |
            feat(front): Update design tokens
            - Update desgin tokens
            - Auto-generated by [create-pull-request][^1]
            [^1]: https://github.com/peter-evans/create-pull-request
          draft: false
