name: auto generate design tokens from data.json

on:
  pull_request:
    branches:
      - main

env:
  workdir: client

jobs:
  run-style-dictionary:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.workdir }}
    if: contains(github.head_ref, 'auto/design-tokens')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Add style-dictionary
        run: yarn add -D style-dictionary
      - name: run style-dictionary
        run: yarn style-dictionary build
      - name: add and commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat(front): update design tokens"
